- name: Play menambah GPG Key
  hosts: localhost #sesuaikan
  tasks:
    - name: Menambahkan GPG Key mysql 5.7
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: 467B942D3A79BD29

    - name: Menambahkan repository mysql 5.7
      ansible.builtin.apt_repository:
        repo: "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7"
        state: present
        update_cache: yes

    - name: Install Mysql 5.7 pada ubuntu 20.04
      ansible.builtin.apt:
        name:
          - mysql-client=5.7*
          - mysql-community-server=5.7*
          - mysql-server=5.7*

    - name: Mengkonfigurasi user dan password MySql 5
