#Install dan konfigurasi PHP 5.6
#Tested on Ubuntu 20.04

- name: Play Update Package
  hosts: localhost #sesuaikan
  tasks:
    - name: Update Paket Repository
      ansible.builtin.apt:
        update-cache: yes
        upgrade: yes

- name: Play Setup Webserver
  hosts: localhost #sesuaikan
  tasks:
    - name: Install GNUPG
      ansible.builtin.apt:
        name:
          - gnupg
          - build-essential

    - name: Add Repository PHP5.6
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Install PHP 5.6
      ansible.builtin.apt:
        name:
          - php5.6
          - php5.6-common
          - php5.6-xml
          - php5.6-xmlrpc
          - php5.6-mysqlnd
          - php5.6-mbstring
          - php5.6-gd
          - php5.6-json
          - php5.6-curl
          - php5.6-cli
          - php5.6-zip
          - php5.6-pear
          - php5.6-dev

    - name: Install Lybmycrypt Plugin
      ansible.builtin.apt:
        name:
          - gcc
          - make
          - autoconf
          - libc-dev
          - pkg-config
          - libmcrypt-dev
